### PR TITLE
96 us create use case 2

### PR DESCRIPTION
**Pull request by witnick**
- updated folder structure to allow better use case loading
- added sql scripts for use case 2
- updated readme.md to explain how to load the different use cases

### CODE REVIEW

**Comment by witnick** [comment]
#96

**Comment by witnick** [comment]
objectMenu

**Review by GuardiansAscend — APPROVED** [review]
Looks good, im happy that you also modified the refresh script. Just for info purposes, this isnt the naming convention we will be going with going forward, but we will fix this in future iterations. Approved!

**Comment by witnick** [comment]
I didn't want to change too much in the names and create more conflicts. Now that the folder structure is down. it should be easy to modify for everyone

**Pull request merged**
